apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movies
  name: movies-deploy
spec:
  replicas: 7
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: contnetflix
        image: vinayr6/image:v1
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  selector:
    app: movies
  ports:
    - port: 8080
